<?php
/**
 * Central menu and permission catalogue used by the sidebar and access UI.
 * The structure is intentionally descriptive so we can show one tree in the UI.
 */
return [
    'sections' => [
        'dashboards' => [
            'label' => 'Dashboards',
            'icon' => 'fas fa-tachometer-alt',
            'collapsible' => true,
            'children' => [
                [
                    'key' => 'admin_dashboard',
                    'label' => 'Admin Dashboard',
                    'icon' => 'fas fa-tachometer-alt',
                    'route' => 'admin-dashboard.php',
                    'pages' => ['Admin Dashboard'],
                    'permissions' => [
                        [
                            'code' => 'view_admin_dashboard',
                            'label' => 'View admin dashboard',
                            'type' => 'view',
                            'description' => 'Access to the company-wide admin dashboard.',
                            'default_roles' => ['Admin', 1],
                        ],
                    ],
                ],
                [
                    'key' => 'user_dashboard',
                    'label' => 'Dashboard',
                    'icon' => 'fas fa-chart-line',
                    'route' => 'dashboard.php',
                    'pages' => ['Dashboard', 'User Dashboard', 'Employee Dashboard'],
                    'permissions' => [
                        [
                            'code' => 'view_dashboard',
                            'label' => 'View personal dashboard',
                            'type' => 'view',
                            'description' => 'Allows users to open their personal dashboard widgets.',
                            'default_roles' => ['*'],
                        ],
                    ],
                ],
            ],
        ],
        'employee_management' => [
            'label' => 'Employee Management',
            'icon' => 'fas fa-users',
            'collapsible' => true,
            'children' => [
                [
                    'key' => 'employees',
                    'label' => 'Employees',
                    'icon' => 'fas fa-users',
                    'route' => 'modules/employees/employees.php',
                    'pages' => ['employees'],
                    'permissions' => [
                        [
                            'code' => 'view_employees',
                            'label' => 'View employee list',
                            'type' => 'view',
                            'description' => 'Shows the employee directory.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                        [
                            'code' => 'manage_employees',
                            'label' => 'Manage employees',
                            'type' => 'manage',
                            'description' => 'Create, edit, or remove employees.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                        [
                            'code' => 'view_employee_personal_details',
                            'label' => 'View personal details',
                            'type' => 'view',
                            'description' => 'Allows viewing sensitive personal information such as contact and ID numbers.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                        [
                            'code' => 'manage_branch_assignments',
                            'label' => 'Manage branch assignments',
                            'type' => 'manage',
                            'description' => 'Allows reassigning employees to different branches or reporting managers.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                        [
                            'code' => 'manage_employee_login_access',
                            'label' => 'Manage login access',
                            'type' => 'manage',
                            'description' => 'Allows enabling, disabling, or resetting employee portal logins.',
                            'default_roles' => ['Admin'],
                        ],
                        [
                            'code' => 'access_all_branch_employee',
                            'label' => 'Access all branch employees',
                            'type' => 'view',
                            'description' => 'Allows a viewer to browse employees in every branch instead of only their own.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                        [
                            'code' => 'view_exited_employees',
                            'label' => 'View exited employees',
                            'type' => 'view',
                            'description' => 'Allows showing employees with an exit date and related history.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                    ],
                ],
                [
                    'key' => 'attendance',
                    'label' => 'Attendance',
                    'icon' => 'fas fa-clipboard-check',
                    'route' => 'modules/attendance/attendance.php',
                    'pages' => ['attendance'],
                    'match_uri' => 'modules/attendance/',
                    'permissions' => [
                        [
                            'code' => 'view_attendance',
                            'label' => 'View attendance',
                            'type' => 'view',
                            'description' => 'Read access to attendance logs.',
                            'default_roles' => ['*'],
                        ],
                        [
                            'code' => 'view_others_attendance',
                            'label' => 'View others attendance (same branch)',
                            'type' => 'view',
                            'description' => 'Allows viewing attendance for other employees within the same branch.',
                            'default_roles' => ['Manager'],
                        ],
                        [
                            'code' => 'view_all_branch_attendance',
                            'label' => 'View all branch attendance',
                            'type' => 'view',
                            'description' => 'Allows viewing attendance for employees across all branches.',
                            'default_roles' => [],
                        ],
                        [
                            'code' => 'manage_attendance',
                            'label' => 'Manage attendance',
                            'type' => 'manage',
                            'description' => 'Create, edit, and delete attendance entries.',
                            'default_roles' => ['Admin'],
                        ],
                        [
                            'code' => 'request_attendance',
                            'label' => 'Request attendance',
                            'type' => 'view',
                            'description' => 'Allows viewing the Attendance Requests tab/page and submitting attendance requests.',
                            'default_roles' => ['Admin', 'Manager', 'HR'],
                        ],
                        [
                            'code' => 'request_attendance_for_others',
                            'label' => 'Request attendance for others',
                            'type' => 'manage',
                            'description' => 'Allows submitting attendance requests on behalf of other employees.',
                            'default_roles' => ['Admin', 'Manager', 'HR'],
                        ],
                        [
                            'code' => 'request_attendance_multi_branch',
                            'label' => 'Request attendance for multiple branches',
                            'type' => 'manage',
                            'description' => 'Allows submitting attendance requests for employees across multiple branches.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                        [
                            'code' => 'process_attendance_requests',
                            'label' => 'Process attendance requests',
                            'type' => 'manage',
                            'description' => 'Allows reviewing, approving, or rejecting attendance requests.',
                            'default_roles' => ['Admin', 'Manager', 'HR'],
                        ],
                    ],
                ],
                [
                    'key' => 'schedule_overrides',
                    'label' => 'Schedule Overrides',
                    'icon' => 'fas fa-calendar-check',
                    'route' => 'modules/employees/schedule-overrides.php',
                    'pages' => ['schedule-overrides'],
                    'permissions' => [
                        [
                            'code' => 'view_schedule_overrides',
                            'label' => 'View overrides',
                            'type' => 'view',
                            'description' => 'Allows users to open the override listing.',
                            'default_roles' => ['Admin'],
                        ],
                        [
                            'code' => 'manage_schedule_overrides',
                            'label' => 'Manage overrides',
                            'type' => 'manage',
                            'description' => 'Allows users to create or edit overrides.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
            ],
        ],
        'leave_management' => [
            'label' => 'Leaves & Holidays',
            'icon' => 'fas fa-calendar-alt',
            'collapsible' => false,
            'children' => [
                [
                    'key' => 'leave_module',
                    'label' => 'Leaves & Holidays',
                    'icon' => 'fas fa-calendar-alt',
                    'route' => 'modules/leave/index.php',
                    'match_uri' => 'modules/leave/',
                    'permissions' => [
                        [
                            'code' => 'access_leave_module',
                            'label' => 'Access leave management',
                            'type' => 'view',
                            'description' => 'Allows entry into the leave and holiday screens.',
                            'default_roles' => ['*'],
                        ],
                        [
                            'code' => 'manage_leave_policies',
                            'label' => 'Manage leave policies',
                            'type' => 'manage',
                            'description' => 'Allows creating leave types, accrual rules, and carry-over limits.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                        [
                            'code' => 'approve_leave_requests',
                            'label' => 'Approve leave requests',
                            'type' => 'manage',
                            'description' => 'Allows reviewing and approving pending employee leave submissions.',
                            'default_roles' => ['Admin', 'Manager'],
                        ],
                        [
                            'code' => 'manage_holidays',
                            'label' => 'Manage holidays',
                            'type' => 'manage',
                            'description' => 'Allows maintaining the company holiday calendar.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                    ],
                ],
            ],
        ],
        'payroll' => [
            'label' => 'Payroll',
            'icon' => 'fas fa-money-bill-wave',
            'collapsible' => true,
            'children' => [
                [
                    'key' => 'salary_components',
                    'label' => 'Salary Components',
                    'icon' => 'fas fa-list-ul',
                    'route' => 'modules/salary/components.php',
                    'pages' => ['salary-components'],
                    'permissions' => [
                        [
                            'code' => 'manage_salary_components',
                            'label' => 'Manage components',
                            'type' => 'manage',
                            'description' => 'Create and edit salary components.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                    ],
                ],
                [
                    'key' => 'salary_structure',
                    'label' => 'Salary Structure',
                    'icon' => 'fas fa-sitemap',
                    'route' => 'modules/salary/structure.php',
                    'pages' => ['salary-structure'],
                    'permissions' => [
                        [
                            'code' => 'manage_salary_structure',
                            'label' => 'Manage structure',
                            'type' => 'manage',
                            'description' => 'Assign components to employees.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                    ],
                ],
                [
                    'key' => 'process_payroll',
                    'label' => 'Process Payroll',
                    'icon' => 'fas fa-calculator',
                    'route' => 'modules/salary/process.php',
                    'pages' => ['process-payroll'],
                    'permissions' => [
                        [
                            'code' => 'process_payroll',
                            'label' => 'Process payroll',
                            'type' => 'manage',
                            'description' => 'Calculate and finalize monthly payroll.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                    ],
                ],
            ],
        ],
        'tasks' => [
            'label' => 'Tasks',
            'icon' => 'fas fa-tasks',
            'collapsible' => false,
            'children' => [
                [
                    'key' => 'tasks_home',
                    'label' => 'Tasks',
                    'icon' => 'fas fa-tasks',
                    'route' => 'modules/tasks/index.php',
                    'match_uri' => 'modules/tasks/',
                    'permissions' => [
                        [
                            'code' => 'view_tasks',
                            'label' => 'View tasks',
                            'type' => 'view',
                            'description' => 'Allows loading the task board.',
                            'default_roles' => ['*'],
                        ],
                        [
                            'code' => 'manage_all_tasks',
                            'label' => 'Manage all tasks',
                            'type' => 'manage',
                            'description' => 'Full CRUD access to every task.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
            ],
        ],
        'reports' => [
            'label' => 'Reports',
            'icon' => 'fas fa-chart-bar',
            'collapsible' => false,
            'children' => [
                [
                    'key' => 'attendance_reports',
                    'label' => 'Attendance Reports',
                    'icon' => 'fas fa-chart-bar',
                    'route' => 'modules/reports/attendance-reports.php',
                    'pages' => ['attendance-reports'],
                    'permissions' => [
                        [
                            'code' => 'view_attendance_reports_daily',
                            'label' => 'View daily report',
                            'type' => 'view',
                            'description' => 'Opens the daily attendance tab and data widgets.',
                            'default_roles' => ['Admin', 'Manager', 'HR'],
                        ],
                        [
                            'code' => 'view_attendance_reports_periodic',
                            'label' => 'View periodic report',
                            'type' => 'view',
                            'description' => 'Allows loading multi-day/weekly/monthly attendance summaries.',
                            'default_roles' => ['Admin', 'Manager'],
                        ],
                        [
                            'code' => 'view_attendance_reports_timesheet',
                            'label' => 'View timesheet report',
                            'type' => 'view',
                            'description' => 'Allows opening the detailed timesheet style report.',
                            'default_roles' => ['Admin'],
                        ],
                        [
                            'code' => 'generate_attendance_reports',
                            'label' => 'Generate attendance reports',
                            'type' => 'manage',
                            'description' => 'Allows running/exporting the selected attendance report types a user can view.',
                            'default_roles' => ['Admin', 'Manager'],
                        ],
                        [
                            'code' => 'view_all_branch_attendance',
                            'label' => 'View all branch attendance',
                            'type' => 'view',
                            'description' => 'Extends attendance report access to every branch instead of just the assigned one.',
                            'default_roles' => ['Admin'],
                        ],
                        [
                            'code' => 'manage_attendance_report_artifacts',
                            'label' => 'Manage report artifacts',
                            'type' => 'manage',
                            'description' => 'Allows deleting, restoring, or purging generated attendance report files for any user.',
                            'default_roles' => ['Admin'],
                        ],
                        [
                            'code' => 'view_all_user_generated_reports',
                            'label' => 'View all user reports',
                            'type' => 'view',
                            'description' => 'Allows browsing attendance reports generated by any user, not just self-created ones.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                        [
                            'code' => 'view_sensitive_attendance_metrics',
                            'label' => 'View sensitive attendance metrics',
                            'type' => 'view',
                            'description' => 'Allows exposing OT, deviation reasons, and other sensitive data points within reports.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                    ],
                ],
            ],
        ],
        'asset_management' => [
            'label' => 'Asset Management',
            'icon' => 'fas fa-clipboard-list',
            'collapsible' => true,
            'children' => [
                [
                    'key' => 'asset_overview',
                    'label' => 'Overview',
                    'icon' => 'fas fa-tachometer-alt',
                    'route' => 'modules/assets/assets.php',
                    'pages' => ['Assets Management'],
                    'permissions' => [
                        [
                            'code' => 'view_assets',
                            'label' => 'View assets',
                            'type' => 'view',
                            'description' => 'Opens the asset dashboard.',
                            'default_roles' => ['Admin'],
                        ],
                        [
                            'code' => 'manage_assets',
                            'label' => 'Manage assets',
                            'type' => 'manage',
                            'description' => 'Allows adding or editing assets.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'asset_categories',
                    'label' => 'Categories',
                    'icon' => 'fas fa-tags',
                    'route' => 'modules/assets/manage_categories.php',
                    'pages' => ['Asset Categories'],
                    'permissions' => [
                        [
                            'code' => 'manage_assets',
                            'label' => 'Manage assets',
                            'type' => 'manage',
                            'description' => 'Allows editing asset categories.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'asset_items',
                    'label' => 'Fixed Assets',
                    'icon' => 'fas fa-laptop',
                    'route' => 'modules/assets/manage_assets.php',
                    'pages' => ['Manage Assets'],
                    'permissions' => [
                        [
                            'code' => 'manage_assets',
                            'label' => 'Manage assets',
                            'type' => 'manage',
                            'description' => 'Allows editing asset inventory.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'asset_assignments',
                    'label' => 'Assignments',
                    'icon' => 'fas fa-people-carry',
                    'route' => 'modules/assets/manage_assignments.php',
                    'pages' => ['Asset Assignments'],
                    'permissions' => [
                        [
                            'code' => 'manage_assets',
                            'label' => 'Manage assets',
                            'type' => 'manage',
                            'description' => 'Allows assigning equipment.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'asset_maintenance',
                    'label' => 'Maintenance',
                    'icon' => 'fas fa-tools',
                    'route' => 'modules/assets/manage_maintenance.php',
                    'pages' => ['Maintenance Records'],
                    'permissions' => [
                        [
                            'code' => 'manage_assets',
                            'label' => 'Manage assets',
                            'type' => 'manage',
                            'description' => 'Allows tracking maintenance logs.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
            ],
        ],
        'company_settings' => [
            'label' => 'Company Settings',
            'icon' => 'fas fa-building',
            'collapsible' => true,
            'children' => [
                [
                    'key' => 'organizational_chart',
                    'label' => 'Organizational Chart',
                    'icon' => 'fas fa-sitemap',
                    'route' => 'organizational-chart.php',
                    'pages' => ['organizational-chart'],
                    'permissions' => [
                        [
                            'code' => 'view_organizational_chart',
                            'label' => 'View org chart',
                            'type' => 'view',
                            'description' => 'Displays the reporting hierarchy.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'hierarchy_setup',
                    'label' => 'Hierarchy Setup',
                    'icon' => 'fas fa-cogs',
                    'route' => 'hierarchy-setup.php',
                    'pages' => ['hierarchy-setup'],
                    'permissions' => [
                        [
                            'code' => 'manage_hierarchy',
                            'label' => 'Manage hierarchy',
                            'type' => 'manage',
                            'description' => 'Configure reporting relationships.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'board_management',
                    'label' => 'Board of Directors',
                    'icon' => 'fas fa-crown',
                    'route' => 'board-management.php',
                    'pages' => ['board-management'],
                    'permissions' => [
                        [
                            'code' => 'manage_board',
                            'label' => 'Manage board members',
                            'type' => 'manage',
                            'description' => 'Edit board/leadership entries.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'contacts',
                    'label' => 'Contacts',
                    'icon' => 'fas fa-address-book',
                    'route' => 'contacts.php',
                    'pages' => ['Contacts'],
                    'permissions' => [
                        [
                            'code' => 'manage_contacts',
                            'label' => 'Manage contacts',
                            'type' => 'manage',
                            'description' => 'Allows viewing and maintaining the shared contact directory.',
                            'default_roles' => ['Admin', 'HR'],
                        ],
                    ],
                ],
                [
                    'key' => 'branches',
                    'label' => 'Branches',
                    'icon' => 'fas fa-code-branch',
                    'route' => 'branches.php',
                    'pages' => ['branches'],
                    'permissions' => [
                        [
                            'code' => 'manage_branches',
                            'label' => 'Manage branches',
                            'type' => 'manage',
                            'description' => 'Create and edit company branch data.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'departments',
                    'label' => 'Departments',
                    'icon' => 'fas fa-building',
                    'route' => 'departments.php',
                    'pages' => ['departments'],
                    'permissions' => [
                        [
                            'code' => 'manage_departments',
                            'label' => 'Manage departments',
                            'type' => 'manage',
                            'description' => 'Maintain department definitions.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'designations',
                    'label' => 'Designations',
                    'icon' => 'fas fa-id-badge',
                    'route' => 'designations.php',
                    'pages' => ['designations'],
                    'permissions' => [
                        [
                            'code' => 'manage_designations',
                            'label' => 'Manage designations',
                            'type' => 'manage',
                            'description' => 'Maintain job titles and levels.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'system_settings',
                    'label' => 'General Settings',
                    'icon' => 'fas fa-wrench',
                    'route' => 'system-settings.php',
                    'pages' => ['System Setting'],
                    'permissions' => [
                        [
                            'code' => 'system_settings',
                            'label' => 'Manage system settings',
                            'type' => 'manage',
                            'description' => 'General configuration access.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'backup_management',
                    'label' => 'Backup & Restore',
                    'icon' => 'fas fa-database',
                    'route' => 'backup-management.php',
                    'pages' => ['Backup Management'],
                    'permissions' => [
                        [
                            'code' => 'manage_backups',
                            'label' => 'Manage backups',
                            'type' => 'manage',
                            'description' => 'Trigger and restore backups.',
                            'default_roles' => ['Admin'],
                        ],
                        [
                            'code' => 'system_settings',
                            'label' => 'System settings fallback',
                            'type' => 'implied',
                            'description' => 'Legacy permission used until manage_backups is granted to roles.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
            ],
        ],
        'sms' => [
            'label' => 'SMS Management',
            'icon' => 'fas fa-sms',
            'collapsible' => false,
            'children' => [
                [
                    'key' => 'sms_dashboard',
                    'label' => 'SMS Management',
                    'icon' => 'fas fa-sms',
                    'route' => 'modules/sms/sms-dashboard.php',
                    'pages' => ['SMS Dashboard','SMS Configuration','SMS Templates','SMS Logs'],
                    'permissions' => [
                        [
                            'code' => 'manage_sms',
                            'label' => 'Manage SMS module',
                            'type' => 'manage',
                            'description' => 'Access to SMS configuration and logs.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
            ],
        ],
        'topbar' => [
            'label' => 'Topbar Components',
            'icon' => 'fas fa-ellipsis-h',
            'collapsible' => true,
            'children' => [
                [
                    'key' => 'topbar_components',
                    'label' => 'Header Shortcuts & Widgets',
                    'icon' => 'fas fa-stream',
                    'permissions' => [
                        [
                            'code' => 'topbar_contacts_shortcut',
                            'label' => 'Show contacts shortcut',
                            'type' => 'view',
                            'description' => 'Displays the contacts icon in the header for one-click access.',
                        ],
                        [
                            'code' => 'topbar_global_search',
                            'label' => 'Use global search',
                            'type' => 'view',
                            'description' => 'Allows using the top search bar and viewing search results.',
                        ],
                        [
                            'code' => 'topbar_notifications_panel',
                            'label' => 'Notifications dropdown',
                            'type' => 'view',
                            'description' => 'Enables the notification bell, dropdown, and unread counter.',
                        ],
                    ],
                ],
            ],
        ],
        'security' => [
            'label' => 'Security & Access',
            'icon' => 'fas fa-user-shield',
            'collapsible' => true,
            'children' => [
                [
                    'key' => 'permissions_matrix',
                    'label' => 'Roles & Permissions',
                    'icon' => 'fas fa-key',
                    'route' => 'permissions.php',
                    'pages' => ['permissions'],
                    'permissions' => [
                        [
                            'code' => 'manage_user_permissions',
                            'label' => 'Manage role permissions',
                            'type' => 'manage',
                            'description' => 'Edit which permissions are tied to a role.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
                [
                    'key' => 'user_access',
                    'label' => 'Permission Overrides',
                    'icon' => 'fas fa-user-lock',
                    'route' => 'user-access.php',
                    'pages' => ['user-access'],
                    'permissions' => [
                        [
                            'code' => 'manage_permission_overrides',
                            'label' => 'Manage user overrides',
                            'type' => 'manage',
                            'description' => 'Grant or revoke individual permissions beyond the role.',
                            'default_roles' => ['Admin'],
                        ],
                    ],
                ],
            ],
        ],
    ],
];
